name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get install -y libncurses-dev && \
        curl -L https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.324+f61c5f3f5.tar.xz | \
        tar -xJ --strip-components=1 -C /usr/local/bin
    - name: build
      run: zig build test
